name: 'Run Copilot E2E Test'
description: 'Run Copilot E2E Test'
inputs:
  script:
    description: 'Script to run'
    default: 'yarn affine @affine-test/affine-cloud-copilot e2e --forbid-only'
    required: false
  openai-key:
    description: 'OpenAI secret key'
    required: true
  fal-key:
    description: 'Fal secret key'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Prepare Server Test Environment
      uses: ./.github/actions/server-test-env

    - name: Server Copilot E2E Test
      shell: bash
      run: ${{ inputs.script }}
      env:
        COPILOT: true
        DEV_SERVER_URL: http://localhost:8080
        COPILOT_OPENAI_API_KEY: ${{ inputs.openai-key }}
        COPILOT_FAL_API_KEY: ${{ inputs.fal-key }}
        COPILOT_PERPLEXITY_API_KEY: ${{ inputs.perplexity-key }}

    - name: Upload test results
      if: ${{ failure() }}
      uses: actions/upload-artifact@v4
      with:
        name: test-results-e2e-server-copilot
        path: ./test-results
        if-no-files-found: ignore
