version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:db
    environment:
      DATABASE_URL: postgresql://affine:affine@db:5432/affine
      REDIS_SERVER_HOST: redis

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: affine
      POSTGRES_USER: affine
      POSTGRES_DB: affine
  redis:
    image: redis
    ports:
      - 6379:6379

volumes:
  postgres-data:
