name: Copilot Test Automatically

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+-canary.[0-9]+'
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

permissions:
  actions: write

jobs:
  dispatch-test:
    runs-on: ubuntu-latest
    name: Setup Test
    steps:
      - name: dispatch test by tag
        if: ${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: copilot-test.yml
      - name: dispatch test by schedule
        if: ${{ github.event_name == 'schedule' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: copilot-test.yml
          ref: canary
